### 재고 차감
POST http://localhost:8082/product/buy
Content-Type: application/json

{
  "requestId": "test-request-123",
  "productInfos": [
    {
      "productId": 1,
      "quantity": 1
    },
    {
      "productId": 2,
      "quantity": 2
    }
  ]
}

### 재고 차감 취소
POST localhost:8082/product/buy/cancel
Content-Type: application/json

{
  "requestId": "test-request-123"
}