### 재고 차감
POST http://localhost:8082/product/buy
Content-Type: application/json

{
  "requestId": "test-request-123",
  "productInfos": [
    {
      "productId": 1,
      "quantity": 1
    },
    {
      "productId": 2,
      "quantity": 2
    }
  ]
}

### 재고 차감 취소
POST http://localhost:8082/product/buy/cancel
Content-Type: application/json

{
  "requestId": "test-request-123"
}

### 포인트 사용
POST http://localhost:8081/point/use
Content-Type: application/json

{
  "requestId": "test-request-101",
  "userId": 1,
  "amount": 100
}

### 포인트 사용 취소
POST http://localhost:8081/point/use/cancel
Content-Type: application/json

{
  "requestId": "test-request-101"
}

### 주문 생성
POST http://localhost:8080/order
Content-Type: application/json

{
  "items": [
    {
      "productId": 1,
      "quantity": 1
    },
    {
      "productId": 2,
      "quantity": 2
    }
  ]
}

> {%
    // IntelliJ HTTP Client: Save orderId variable from response for next request
    client.global.set("orderId", response.body.orderId);
%}

### 주문 결제 진행
POST http://localhost:8080/order/place
Content-Type: application/json

{
  "orderId": {{orderId}}
}